maintainer       "Cloudgate-Service Ltd"
maintainer_email "lebedevdsl@gmail.com"
license          "Apache 2.0"
description      "Installs/Configures munin-{master,node}"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "0.0.1"
provides         "munin::server"
provides         "munin::client"
provides         "service[rrdcached]"
provides         "service[spawn-fcgi-munin-graph]"
provides         "service[spawn-fcgi-munin-html]"
supports         'debian', ">= 6.0"
suggests         "nginx::server"